spring:
  application:
    name: transaction-service
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:${user.home}/.moneymanager/transactions;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true

server:
  port: 8081
  tomcat:
    max-http-form-post-size: 5MB

logging:
  group:
    myapp: hhz
    spring: org.springframework, org.springframework.web, org.springframework.boot
    database: liquibase, org.hibernate, com.zaxxer
    http: org.apache.coyote, org.apache.catalina
  level:
    myapp: debug
    spring: warn
    database: warn
    http: warn
  pattern:
    console: '%d{dd.MM.YYYY HH:mm:ss.SSS} %highlight(%-5level) --- [%25thread] --- %-75logger{75} : %cyan(%msg%n)'