ALTER TABLE TRANSACTIONS
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE TRANSACTIONS
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE CATEGORIES
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE CATEGORIES
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP();